
Installing the libraries
```{r}
library(tidyverse)
library(spatstat)
```

Downloading the spatial centered data of specific cell type

```{r}
coordinates <- read.csv("cell_type_coordinates.csv",
                        row.names = 1) # data for cancer cells
```

```{r}
dim(coordinates)
```

```{r}
summary(coordinates)
```

Convertion the coordinates from the data to matrix

```{r}
coordinates_matrix <- as.matrix(coordinates[1:3])
```


### Let the spatial statistics begin!
Define the ranges for each coordinate (you could also use range(coordinates_matrix[,i]))
```{r}
x_range <- c(min(coordinates_matrix[, 1]), max(coordinates_matrix[, 1]))
y_range <- c(min(coordinates_matrix[, 2]), max(coordinates_matrix[, 2]))
z_range <- c(min(coordinates_matrix[, 3]), max(coordinates_matrix[, 3]))

# Create the 3D box (an object of class "box3")
my_box <- box3(xrange = x_range, yrange = y_range, zrange = z_range)
```
Making a point pattern object
```{r}
mypattern <- pp3(coordinates_matrix[, 1], coordinates_matrix[, 2],
                 coordinates_matrix[, 3], my_box)
```


```{r}
plot(mypattern)
```

```{r}
# Compute the 3D Ripley's K function for your pp3 object
K3 <- K3est(mypattern)

# Plot the estimated K function
plot(K3)
```